name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Mettre à jour vers la version 3

    - name: Set up Python
      uses: actions/setup-python@v4  # Mettre à jour vers la version 4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn numpy pandas joblib pytest

    - name: Run tests
      run: pytest